---
version: '3'
services:
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5050:80
    deploy:
      replicas: 2
  myredis:
    image: redis
    ports:
      - 6379:6379
  worker:
    image: dockersamples/examplevotingapp_worker
  mypostgres:
    image: postgres
    ports:
      - 5342:5432
    environment:
      POSTGRES_PASSWORD: intelliqit
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
  result-app:
      image: dockersamples/examplevotingapp_result
      ports:
        - 6060:80
      deploy:
        replicas: 2
