apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mypostgres
  name: mypostgres
spec:
  ports:
  - name: "5342"
    port: 5342
    targetPort: 5432
  selector:
    io.kompose.service: mypostgres
status:
  loadBalancer: {}
